logging:
  file: logs/coworkio.log
spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017
      username: coworkio_user
      password: coworkio_user
      database: coworkioDB
      authentication-database: coworkioDB
  security:
    cors:
      origins:
        - "http://localhost:5555"
---

spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017
      username: coworkio_user
      password: coworkio_user
      database: coworkioDB
      authentication-database: coworkioDB
  security:
      cors:
        origins:
          - "http://localhost:5555"


---

spring:
  profiles: prod
  data:
    mongodb:
      uri: ${MONGO_URI}
      username: ${MONGO_USER}
      password: ${MONGO_PWD}
      database: heroku_p7mh74hw
      authentication-database: heroku_p7mh74hw
  security:
      cors:
        origins:
          - ""