logging:
  file: logs/coworkio.log
---

spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017
      username: coworkio_user
      password: coworkio_user
      database: coworkioDB
      authentication-database: coworkioDB
  security:
      cors:
        origins:
          - "http://localhost:5555"


---

spring:
  profiles: prod
  data:
    mongodb:
      uri: mongodb://coworkio_user:cowork1o_user@ds157479.mlab.com:57479/heroku_p7mh74hw
  security:
      cors:
        origins:
          - ""